console.log("personal details")
let person={
NAME:"RAGAVI T",
EMAIL:"ragaviragavi02@gmail.com",
MOBILE_NUMBER:"6379928335",
GENDER :"FEMALE",
DATE_OF_BIRTH :"12MARCH 2001",
ADDRESS:"4/172,KUDI STREET,T.NAGAPALAYAM,NAMAKKAL"}
console.log(person)
console.log("Education qualification")
let education={
SSLC :"SUN STARS HIGH SCHOOL,NAMAKKAL",
PERCENTAGE:"94.6%",
YEAR:"2016-2017",
HSSC:"RKV MATRICULATION AND HIGHER SECONDARY SCHOOL,NAMAKKAL",
PERCENTAGE:"80%",
COLLEGE:"BANNARI AMMAN INSTITUTE OF TECHNOLOGY,ERODE",
DEGREE:"BTECH- INFORMATION TECHNOLGY",
YEAR_OF_PASSING:"2023",
PERCENTAGE_UPTO_SIXTH_SEMESTER:"80%"
}
console.log(education)
let detail={
SKILLS :"TABLEAU,PYTHON",
LANGUAGE:"ENGLISH,TAMIL",
HOBBIES:"GARDENING,COOKING,LISTENING MUSIC",
EXTRACURRICULAR_ACTIVITIES :"PARTICIPATED IN NSS EVENT-VAN MAHOTSAV EVENT"
}   
console.log(detail)
let detail1={
COURSE :"PROGRAMMING FOR EVERYBODY(GETTING STARTED WITH PYTHON",
CETRIFICATE:"PARTICIPATED IN GUINNESS WORLD RECORD CONDUCTED BY GUVI",
PROJECT:"AUTOMATIC VEHICLE ACCIDENT PREVENTION AND DETECTION SYSTEM"
}
console.log(detail1)







